/**
 * Module: top_vga_basys3
 * Summary: Connects the game core, clocking, PS/2 mouse, UART, VGA, LEDs, and seven-segment display to the Basys 3 pins.
 * Author: Adam Krupa, Krzysztof Jędrzejek
 * Based on: SJSU EE178 Lab #4 by Prof. Eric Crabilla, adapted for AGH UEC2 by Piotr Kaczmarczyk.
 */
module top_vga_basys3 (
        input  wire clk,
        input  wire btnC,
        input  wire btnU,
        input  wire [15:0] sw,
        output wire Vsync,
        output wire Hsync,
        output wire [3:0] vgaRed,
        output wire [3:0] vgaGreen,
        output wire [3:0] vgaBlue,
        output wire JA1,
        output wire [6:0] seg,
        output wire [3:0] an,
        output wire dp,
        output wire [7:0]  led_low,   // maps to physical LED 0..7
        output wire [15:12] led_high, // maps to physical LED 12..15

        input  wire uart_rx,
        output wire uart_tx,

        inout wire PS2Data,
        inout wire PS2Clk
    );

    timeunit 1ns;
    timeprecision 1ps;

    /**
     * Local variables and signals
     */

    wire locked;
    wire pclk_mirror;

    wire clk_65M;
    wire core_rst;
    wire [7:0] seven_segment_value;
    wire async_core_rst_n;
    wire uart_link_connected;
    wire uart_rx_activity;
    wire uart_error;
    wire uart_remote_debug;
    wire [7:0] uart_remote_score;

    /**
     * Signals assignments
     */

    assign JA1 = pclk_mirror;
    assign async_core_rst_n = !btnC && locked;
    assign led_low      = uart_remote_score;
    assign led_high[12] = uart_remote_debug;
    assign led_high[13] = uart_error;
    assign led_high[14] = uart_rx_activity;
    assign led_high[15] = uart_link_connected;


    /**
     * FPGA submodules placement
     */

    clk_wiz_0 CLK0(
        .clk_in(clk),       // Match the default input name generated by Vivado.
        .clk_out1(clk_65M),
        .locked(locked)
    );

    reset_sync u_reset_sync (
        .clk(clk_65M),
        .async_rst_n(async_core_rst_n),
        .rst_n(core_rst)
    );


    ODDR pclk_oddr (
        .Q(pclk_mirror),
        .C(clk_65M),
        .CE(1'b1),
        .D1(1'b1),
        .D2(1'b0),
        .R(1'b0),
        .S(1'b0)
    );


    /**
     *  Project functional top module
     */

    top_fsm u_top_fsm (
        .clk(clk_65M),
        .rst(core_rst), // Synchronized active-high run/reset-release signal.
        .switches(sw),
        .uart_rx_i(uart_rx),
        .uart_debug_finish(btnU),
        .uart_tx_o(uart_tx),
        .uart_link_connected(uart_link_connected),
        .uart_rx_activity(uart_rx_activity),
        .uart_error(uart_error),
        .uart_remote_debug(uart_remote_debug),
        .uart_remote_score(uart_remote_score),
        .r(vgaRed),
        .g(vgaGreen),
        .b(vgaBlue),
        .hs(Hsync),
        .vs(Vsync),
        .seven_segment_value(seven_segment_value),
        .ps2_data(PS2Data),
        .ps2_clk(PS2Clk)
    );

    seven_segment_display u_seven_segment_display (
        .clk(clk_65M),
        .rst(core_rst),
        .value(seven_segment_value),
        .seg,
        .an,
        .dp
    );

endmodule
